name: build-publish-client
on:
   workflow_dispatch:
   push:
     branches:
       - master
     tags:
       - 'v*'  
     paths:
       - 'client/**'
defaults:
  run:
    working-directory: client
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-client    
jobs:
  build-it:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
     - name: Clone repository
       uses: actions/checkout@v3
       with:
         ref: ${{ steps.vars.outputs.tag }}

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
       with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Login to ghcr.io
       uses: docker/login-action@v2
       with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

     - name: Docker meta
       id: meta
       uses: docker/metadata-action@v4
       with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

     - name: Build and push
       uses: docker/build-push-action@v4
       with:
          file: client/Dockerfile
#          platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max